# This release drafter follows the conventions
# from https://keepachangelog.com

name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  ## What Changed 👀

  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
categories:
  - title: 🚀 Features
    labels:
      - "type: feat"
  - title: 🐛 Fixes
    labels:
      - "type: fix"
  - title: 📄 Documentation
    labels:
      - "type: docs"
  - title: 🔄 CI
    labels:
      - "type: ci"
  - title: 🧩 Dependency Updates
    labels:
      - "type: build"
    collapse-after: 5

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch

exclude-labels:
  - skip-changelog
