stages:
  - prerequisites
  - lint
  - build
  - package
  - deploy

variables:
  NODE_VERSION: node:14-alpine
  CACHE_KEY: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR

# include:
#   - remote: 'https://jobs.r2devops.io/latest/docker_build.yml?scope=0.yml'


.node:
  interruptible: true
  image: $NODE_VERSION
  extends: .pull-cache

.pull-cache:
  cache:
    key: $CACHE_KEY
    paths:
      - node_modules/
    policy: pull

dependencies:
  interruptible: true
  stage: prerequisites
  image: $NODE_VERSION
  script:
    - npm ci
  cache:
    key: $CACHE_KEY
    paths:
      - node_modules/
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH
      changes:
        - package-lock.json

lint:
  interruptible: true
  stage: lint
  extends: .node
  script:
    - npm run lint
    - npm run format:check

audit:
  interruptible: true
  stage: lint
  extends: .node
  script:
    - npm audit

build:
  interruptible: true
  stage: build
  extends: .node
  script: 
    - npm run build
  artifacts:
    paths:
      - build
  rules:
    - if: ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop")


# docker_build:
#   stage: package
#   interruptible: true
#   variables:
#     DOCKERFILE_PATH: 'Dockerfile'
#     DOCKER_USE_CACHE: 'true'
#   rules:
#     - if: ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop")

app:
  interruptible: true
  stage: deploy
  dependencies: 
    - build
  image: dokku/ci-docker-image
  variables:
    GIT_REMOTE_URL: ssh://dokku@dokku.thomasgouveia.fr/polyflix.dokku.thomasgouveia.fr
  script: dokku-deploy
  after_script:
    - dokku-unlock
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

