export enum Endpoint {
  Quizzes = 'quizzes',
  Videos = 'videos',
  Users = 'users',
  Subtitles = 'subtitles',
  Modules = 'modules',
  Stats = 'stats',
  Courses = 'courses',
  Attempts = 'attempts',
  Links = 'links',
  Search = 'search',
  Notes = 'notes',
  Groups = 'groups',
  Certifications = 'certifications',
  AdminSubtitles = 'admin/subtitles',
  Attachments = 'attachments',
}
