name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  frontend:
    uses: polyflix/.github/.github/workflows/node-ci.yml@main
    secrets: inherit
