name: Tests end-to-end

on:
  schedule:
    - cron: '42 23 * * *'
  pull_request:
    paths:
      - .github/workflows/e2e.yml
      - tests/**

jobs:
  test_e2e:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install npm
        run: npm ci
      - name: Run test
        env:
          POLYFLIX_URL: ${{ secrets.POLYFLIX_URL }}
          TEST_ADMIN_EMAIL: ${{ secrets.TEST_ADMIN_EMAIL }}
          TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}
          TEST_CONTRIBUTOR_EMAIL: ${{ secrets.TEST_CONTRIBUTOR_EMAIL }}
          TEST_CONTRIBUTOR_PASSWORD: ${{ secrets.TEST_CONTRIBUTOR_PASSWORD }}
          TEST_MEMBER_EMAIL: ${{ secrets.TEST_MEMBER_EMAIL }}
          TEST_MEMBER_PASSWORD: ${{ secrets.TEST_MEMBER_PASSWORD }}
        run: npm run test:e2e
