name: Tests end-to-end

on:
  schedule:
    - cron: '42 23 * * *'

jobs:
  test_e2e:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install npm
        run: npm ci
      - name: Build
        run: npm run test:e2e
