name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  automated_review:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Audit dependencies
        run: pnpm audit

      - name: Linting code
        run: pnpm run --if-present lint

      - name: Check code formatting
        run: pnpm run --if-present format
