name: Release

on:
  push:
    branches:
      - main

jobs:
  drafter:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
